#include <bitset>   // compact STL for Sieve, more efficient than vector<bool>!
#include <cmath>
#include <cstdio>
#include <map>
#include <vector>

using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef map<int, int> mii;

ll _sieve_size;
bitset<10000010> bs;   // 10^7 should be enough for most cases
vi primes;   // compact list of primes in form of vector<int>

void sieve(ll upperbound) {          // create list of primes in [0..upperbound]
  _sieve_size = upperbound + 1;                   // add 1 to include upperbound
  bs.set();                                                 // set all bits to 1
  bs[0] = bs[1] = 0;                                     // except index 0 and 1
  for (ll i = 2; i <= _sieve_size; i++) if (bs[i]) {
    // cross out multiples of i starting from i * i!
    for (ll j = i * i; j <= _sieve_size; j += i) bs[j] = 0;
    primes.push_back((int)i);  // also add this vector containing list of primes
} }      

vi primeFactors(ll N) {   // remember: vi is vector of integers, ll is long long
  vi factors;                    // vi `primes' (generated by sieve) is optional
  ll PF_idx = 0, PF = primes[PF_idx];     // using PF = 2, 3, 4, ..., is also ok
  while (N != 1 && (PF * PF <= N)) {   
    while (N % PF == 0) { N /= PF; factors.push_back(PF); }    // remove this PF
    PF = primes[++PF_idx];                              // only consider primes!
  }
  if (N != 1) factors.push_back(N);    
  return factors;         
}

int main(int argc, char **argv)
{
  sieve(10000000);
  int n;
  while(scanf("%d", &n) && n){
    bool menor_q_0 = false;
    if(n < 0) menor_q_0 = true;
		
    printf("%d =", n);
    if(menor_q_0){
      printf(" -1");
      vi r = primeFactors((int)fabs(n));
      for(vi::iterator i = r.begin(); i != r.end(); i++){
	printf(" x");
	printf(" %d", *i);
      }
    }else{
      vi r = primeFactors((int)fabs(n));
      printf(" %d", r[0]);
      for(vi::iterator i = r.begin()+1; i != r.end(); i++){
	printf(" x %d", *i);
      }
    }
    puts("");
  }
  return 0;
}

